//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  MF_xfl_triangle                      //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package clasificadordehuevos;

public class MF_xfl_triangle extends InputMembershipFunction {
 double a;
 double b;
 double c;

 public MF_xfl_triangle(double min, double max, double step, double single[], double list[]) {
  super.min = min;
  super.max = max;
  super.step = step;
  this.a = single[0];
  this.b = single[1];
  this.c = single[2];
 }
 public double param(int _i) {
  switch(_i) {
   case 0: return a;
   case 1: return b;
   case 2: return c;
   default: return 0;
  }
 }

 public double isEqual(double x) {
    return (a<x && x<=b? (x-a)/(b-a) : (b<x && x<c? (c-x)/(c-b) : 0)); 
 }
 public double isGreaterOrEqual(double x) {
    return (x<a? 0 : (x>b? 1 : (x-a)/(b-a) )); 
 }
 public double isSmallerOrEqual(double x) {
    return (x<b? 1 : (x>c? 0 : (c-x)/(c-b) )); 
 }
 public double center() {
    return b; 
 }
 public double basis() {
    return (c-a); 
 }
}

