//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_clasificacionhuevos_Tcolor                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: TypeLV "Tcolor"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package clasificadordehuevos;

public class TP_clasificacionhuevos_Tcolor {
 private double min = 0.0;
 private double max = 255.0;
 private double step = 1.0;
 double _ps_Oscuro[] = { -127.5,0.0,100.0 };
 double _pl_Oscuro[] = {  };
 double _ps_Rosado[] = { 28.0,127.5,227.0 };
 double _pl_Rosado[] = {  };
 double _ps_Blanco[] = { 156.0,255.0,382.5 };
 double _pl_Blanco[] = {  };
 MF_xfl_triangle Oscuro = new MF_xfl_triangle(min,max,step,_ps_Oscuro,_pl_Oscuro);
 MF_xfl_triangle Rosado = new MF_xfl_triangle(min,max,step,_ps_Rosado,_pl_Rosado);
 MF_xfl_triangle Blanco = new MF_xfl_triangle(min,max,step,_ps_Blanco,_pl_Blanco);
}


