//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_clasificacionhuevos_Ttipo                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: TypeLV "Ttipo"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package clasificadordehuevos;

public class TP_clasificacionhuevos_Ttipo {
 private double min = 1.0;
 private double max = 4.0;
 private double step = 1.0;
 double _ps_PRIMERA[] = { 0.0,1.0,2.0 };
 double _pl_PRIMERA[] = {  };
 double _ps_SEGUNDA[] = { 1.0,2.0,3.0 };
 double _pl_SEGUNDA[] = {  };
 double _ps_TERCERA[] = { 2.0,3.0,4.0 };
 double _pl_TERCERA[] = {  };
 double _ps_CUARTA[] = { 3.0,4.0,5.0 };
 double _pl_CUARTA[] = {  };
 MF_xfl_triangle PRIMERA = new MF_xfl_triangle(min,max,step,_ps_PRIMERA,_pl_PRIMERA);
 MF_xfl_triangle SEGUNDA = new MF_xfl_triangle(min,max,step,_ps_SEGUNDA,_pl_SEGUNDA);
 MF_xfl_triangle TERCERA = new MF_xfl_triangle(min,max,step,_ps_TERCERA,_pl_TERCERA);
 MF_xfl_triangle CUARTA = new MF_xfl_triangle(min,max,step,_ps_CUARTA,_pl_CUARTA);
}


