//++++++++++++++++++++++++++++++++++++++++++++++++++++++//
//                                                      //
// Class:  TP_clasificacionhuevos_Tpeso                           //
//                                                      //
// Author: Automatically generated by Xfuzzy            //
//                                                      //
// Description: TypeLV "Tpeso"                      //
//                                                      //
//++++++++++++++++++++++++++++++++++++++++++++++++++++++//

package clasificadordehuevos;

public class TP_clasificacionhuevos_Tpeso {
 private double min = 50.0;
 private double max = 70.0;
 private double step = 1.0;
 double _ps_S[] = { 47.5,50.0,55.0,57.5 };
 double _pl_S[] = {  };
 double _ps_M[] = { 55.0,57.5,62.5,65.0 };
 double _pl_M[] = {  };
 double _ps_L[] = { 62.5,65.0,70.0,72.5 };
 double _pl_L[] = {  };
 MF_xfl_trapezoid S = new MF_xfl_trapezoid(min,max,step,_ps_S,_pl_S);
 MF_xfl_trapezoid M = new MF_xfl_trapezoid(min,max,step,_ps_M,_pl_M);
 MF_xfl_trapezoid L = new MF_xfl_trapezoid(min,max,step,_ps_L,_pl_L);
}


